<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tools/**/*.cs" />
    <PackageReference Include="cTrader.Automate" Version="*" />
    <PackageReference Include="Parquet.Net" Version="4.24.0" />
  </ItemGroup>
</Project>
